acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
