acme_blog_homepage:
    path:     /
    defaults: { _controller: AcmeBlogBundle:Default:index }
    
acme_blog_foobar:
    path: foo/{username}
    defaults: { _controller: AcmeBlogBundle:Default:foo }