acme_tasks:
    path: /tasks
    defaults: { _controller: AcmeTaskBundle:Default:index }

acme_store_task:
    path: /tasks/post
    defaults: { _controller: AcmeTaskBundle:Default:store }

acme_delete_task:
    path: /tasks/delete
    defaults: { _controller: AcmeTaskBundle:Default:destroy }